### ISSUE TITLE
下载demo运行报错 app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by chaclee** [tencentyun/wafer2-aai-nodejs#1]
```
root@izuf62q4uzgm4b2e4eluf0z /home/wwwroot/test123 (master) $ npm run dev

> wafer2-asr-demo@1.0.0 dev /home/wwwroot/test123
> nodemon --config nodemon.json app.js

[nodemon] 1.14.11
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 13476 to restart
[nodemon] ignoring: ./.git/**/* node_modules/**/node_modules
[nodemon] watching: *.*
[nodemon] watching extensions: js,json
[nodemon] starting `node --harmony app.js`
[nodemon] spawning
[nodemon] child pid: 13487
[nodemon] watching 11 files
/home/wwwroot/test123/middlewares/response.js:6
module.exports = async function (ctx, next) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wwwroot/test123/app.js:4:18)
    at Module._compile (module.js:570:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jas0ncn** [comment]
请升级Node.js到8.x哈

**Comment by cntaoyu** [comment]
@jas0ncn 问下这个流式语音识别的api在哪里有呢？我看qcloud上只有客户端sdk，我需要在服务端进行处理。

**Comment by jas0ncn** [comment]
不是很理解您的意思。。。api 在哪里？

**Comment by cntaoyu** [comment]
@jas0ncn 你们这个使用的是智能语音服务的实时流式声音识别接口吗？我想用php实现

**Comment by jas0ncn** [comment]
是的，是实时流式语言识别
